# Generated by Django 5.2.15 on 2026-06-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, verbose_name='OPIS Truckstop ID')),
                ('name', models.CharField(max_length=255, verbose_name='Truckstop Name')),
                ('address', models.CharField(blank=True, max_length=512)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, db_index=True, max_length=2)),
                ('rack_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('retail_price', models.DecimalField(decimal_places=4, max_digits=7)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('geocode_status', models.CharField(choices=[('PENDING', 'Pending'), ('OK', 'Ok'), ('APPROXIMATE', 'Approximate (city/state centroid)'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('geocode_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='station_lat_lng_idx')],
            },
        ),
    ]
